name: Pull Request workflow

on:
  pull_request:
    types: [labeled, reopened, synchronize, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if there are 2 approved reviews
        run: |
          echo "https://api.github.com/repos/GeraldAdyen/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews"
          reviews=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/GeraldAdyen/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews")
          
          echo "Reviews JSON: $reviews"

          approved_reviews=$(echo "$reviews" | jq '[.[] | select(.state == "APPROVED")] | length')

          if [[ $approved_reviews -ge 2 ]]; then
            echo "There are 2 or more approved reviews. Run the desired script here."
            # Add your script or command to run here
          else
            echo "Not enough approved reviews. Skipping the script."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}